networks:
  cmv:
    external: true

volumes:
  cmv_gateway:
    driver: local
  db_gateway:
    driver: local
  cmv_patients:
    driver: local
  db_patients:
    driver: local
  logs:
    driver: local
  redis:
    driver: local

services:
  redis:
    image: redis:latest
    restart: always
    container_name: redis-server
    networks:
      - cmv
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  db_gateway:
    image: postgres:latest
    restart: always
    container_name: db_gateway
    volumes:
      - db_gateway:/var/lib/postgresql/data
    networks:
      - cmv
    ports:
      - "6001:5432"
    environment:
      POSTGRES_USER: ${GATEWAY_POSTGRES_USER}
      POSTGRES_PASSWORD: ${GATEWAY_POSTGRES_PASSWORD}
      POSTGRES_DB: ${GATEWAY_POSTGRES_DB}

  api_gateway:
    build:
      context: ./cmv_gateway
    restart: always
    networks:
      - cmv
    volumes:
      - logs:/app/app/logs
    container_name: cmv_gateway
    ports:
      - "8001:8000"
    depends_on:
      - db_gateway
    environment:
      GATEWAY_DATABASE_URL: ${GATEWAY_POSTGRES_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      PATIENTS_SERVICE: ${PATIENTS_SERVICE}
      ACCESS_MAX_AGE: ${ACCESS_MAX_AGE}
      REFRESH_MAX_AGE: ${REFRESH_MAX_AGE}
    command: >
      bash -c 'while !</dev/tcp/db_gateway/5432; do sleep 1; done; alembic upgrade head; uvicorn app.main:app --reload --host 0.0.0.0 --port 8000'

    develop:
      watch:
        - path: ./cmv_gateway
          action: rebuild

  db_patients:
    image: postgres:latest
    restart: always
    container_name: db_patients
    volumes:
      - db_patients:/var/lib/postgresql/data
    networks:
      - cmv
    ports:
      - "6002:5432"
    environment:
      POSTGRES_USER: ${PATIENTS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PATIENTS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${PATIENTS_POSTGRES_DB}

  api_patients:
    build:
      context: ./cmv_patients
    restart: always
    networks:
      - cmv
    container_name: cmv_patients
    ports:
      - "8002:8000"
    depends_on:
      - db_patients
    environment:
      PATIENTS_DATABASE_URL: ${PATIENTS_DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION_NAME: ${AWS_REGION_NAME}
    command: >
      bash -c 'while !</dev/tcp/db_patients/5432; do sleep 1; done; alembic upgrade head; uvicorn app.main:app --reload --host 0.0.0.0 --port 8000'

    develop:
      watch:
        - path: ./cmv_patients
          action: rebuild

  nginx:
    image: nginx:latest
    networks:
      - cmv
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api_gateway
