networks:
  cmv:
    external: true

volumes:
  db_gateway:
    driver: local
  db_patients:
    driver: local
  db_chambres:
    driver: local
  redis:
    driver: local

services:
  redis:
    image: redis:latest
    restart: always
    container_name: redis-server
    networks:
      - cmv
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  db_gateway:
    image: postgres:latest
    restart: always
    container_name: db_gateway
    volumes:
      - db_gateway:/var/lib/postgresql/data
    networks:
      - cmv
    ports:
      - "6001:5432"
    environment:
      POSTGRES_USER: ${GATEWAY_POSTGRES_USER}
      POSTGRES_PASSWORD: ${GATEWAY_POSTGRES_PASSWORD}
      POSTGRES_DB: ${GATEWAY_POSTGRES_DB}

  db_patients:
    image: postgres:latest
    restart: always
    container_name: db_patients
    volumes:
      - db_patients:/var/lib/postgresql/data
    networks:
      - cmv
    ports:
      - "6002:5432"
    environment:
      POSTGRES_USER: ${PATIENTS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PATIENTS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${PATIENTS_POSTGRES_DB}

  db_chambres:
    image: postgres:latest
    restart: always
    container_name: db_chambres
    volumes:
      - db_chambres:/var/lib/postgresql/data
    networks:
      - cmv
    ports:
      - "6003:5432"
    environment:
      POSTGRES_USER: ${CHAMBRES_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CHAMBRES_POSTGRES_PASSWORD}
      POSTGRES_DB: ${CHAMBRES_POSTGRES_DB}
