version: "3.8"

networks:
  cmv:
    external: true

volumes:
  cmv_auth:
    driver: local
  db_auth:
    driver: local
  cmv_home:
    driver: local
  db_home:
    driver: local
  logs:
    driver: local

services:
  redis:
    image: redis:latest
    restart: always
    container_name: redis-server
    networks:
      - cmv
    ports:
      - "6379:6379"

  db_auth:
    image: postgres:latest
    restart: always
    container_name: db_auth
    volumes:
      - db_auth:/var/lib/postgresql/data
    networks:
      - cmv
    ports:
      - "6001:5432"
    environment:
      POSTGRES_USER: ${AUTH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AUTH_POSTGRES_DB}

  api_auth:
    build:
      context: ./cmv
    restart: always
    networks:
      - cmv
    volumes:
      - logs:/app/app/logs
    container_name: cmv_auth
    ports:
      - "8001:8000"
    depends_on:
      - db_auth
    environment:
      AUTH_DATABASE_URL: ${AUTH_DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      HOME_SERVICE: ${HOME_SERVICE}
      ACCESS_MAX_AGE: ${ACCESS_MAX_AGE}
      REFRESH_MAX_AGE: ${REFRESH_MAX_AGE}
    command: >
      bash -c 'while !</dev/tcp/db_auth/5432; do sleep 1; done; alembic upgrade head; uvicorn app.main:app --reload --host 0.0.0.0 --port 8000'

    develop:
      watch:
        - path: ./cmv
          action: rebuild

  db_home:
    image: postgres:latest
    restart: always
    container_name: db_home
    volumes:
      - db_home:/var/lib/postgresql/data
    networks:
      - cmv
    ports:
      - "6002:5432"
    environment:
      POSTGRES_USER: ${HOME_POSTGRES_USER}
      POSTGRES_PASSWORD: ${HOME_POSTGRES_PASSWORD}
      POSTGRES_DB: ${HOME_POSTGRES_DB}

  api_home:
    build:
      context: ./cmv_home
    restart: always
    networks:
      - cmv
    container_name: cmv_home
    ports:
      - "8002:8000"
    depends_on:
      - db_home
    environment:
      HOME_DATABASE_URL: ${HOME_DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
    command: >
      bash -c 'while !</dev/tcp/db_home/5432; do sleep 1; done; alembic upgrade head; uvicorn app.main:app --reload --host 0.0.0.0 --port 8000'

    develop:
      watch:
        - path: ./cmv_home
          action: rebuild

  nginx:
    image: nginx:latest
    networks:
      - cmv
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api_auth
