networks:
  cmv:
    external: true

volumes:
  cmv_gateway:
    driver: local
  db_gateway:
    driver: local
  cmv_patients:
  cmv_chambres:
    driver: local
  logs:
    driver: local
  redis:
    driver: local

# The containers that compose the project
services:
  redis:
    image: valkey/valkey:latest
    restart: always
    container_name: redis-server
    networks:
      - cmv
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    environment:
      VALKEY_HOST: ${VALKEY_HOST}
      VALKEY_PORT: ${VALKEY_PORT}

  db_gateway:
    image: postgres:17
    restart: always
    container_name: db_gateway
    volumes:
      - db_gateway:/var/lib/postgresql/data
    networks:
      - cmv
    ports:
      - "6001:5432"
    environment:
      POSTGRES_USER: ${GATEWAY_POSTGRES_USER}
      POSTGRES_PASSWORD: ${GATEWAY_POSTGRES_PASSWORD}
      POSTGRES_DB: ${GATEWAY_POSTGRES_DB}

  api_gateway:
    image: firizgoude/cmv_gateway:latest
    pull_policy: always
    restart: always
    networks:
      - cmv
    volumes:
      - logs:/app/app/logs
    container_name: cmv_gateway
    ports:
      - "8001:8000"
    links:
      - db_gateway
    command: >
      bash -c 'while !</dev/tcp/db_gateway/5432; do sleep 1; done; alembic upgrade head; uvicorn app.main:app --reload --host 0.0.0.0 --port 8000'
    depends_on:
      - db_gateway
    environment:
      GATEWAY_DATABASE_URL: ${GATEWAY_POSTGRES_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      PATIENTS_SERVICE: ${PATIENTS_SERVICE}
      CHAMBRES_SERVICE: ${CHAMBRES_SERVICE}
      ML_SERVICE: ${ML_SERVICE}
      ACCESS_MAX_AGE: ${ACCESS_MAX_AGE}
      REFRESH_MAX_AGE: ${REFRESH_MAX_AGE}
      ENVIRONMENT: ${ENVIRONMENT}

  api_patients:
    image: firizgoude/cmv_patients:latest
    pull_policy: always
    restart: always
    networks:
      - cmv
    volumes:
      - logs:/code/app/logs
    container_name: cmv_patients
    ports:
      - "8002:8000"
    links:
      - db_gateway
    command: >
      bash -c 'while !</dev/tcp/db_gateway/5432; do sleep 1; done; alembic upgrade head; uvicorn app.main:app --reload --host 0.0.0.0 --port 8000'
    depends_on:
      - db_gateway
    environment:
      PATIENTS_DATABASE_URL: ${PATIENTS_DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}

  api_chambres:
    image: firizgoude/cmv_chambres:latest
    pull_policy: always
    restart: always
    networks:
      - cmv
    container_name: cmv_chambres
    ports:
      - "8003:8000"
    links:
      - db_gateway
    command: >
      bash -c 'while !</dev/tcp/db_gateway/5432; do sleep 1; done; alembic upgrade head; uvicorn app.main:app --reload --host 0.0.0.0 --port 8000'
    depends_on:
      - db_gateway
    environment:
      CHAMBRES_DATABASE_URL: ${CHAMBRES_DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}

  api_ml:
    image: firizgoude/cmv_ml:latest
    pull_policy: always
    restart: always
    networks:
      - cmv
    container_name: cmv_ml
    ports:
      - "8004:8000"
    links:
      - db_gateway
    command: >
      bash -c 'while !</dev/tcp/db_gateway/5432; do sleep 1; done; alembic upgrade head; uvicorn app.main:app --reload --host 0.0.0.0 --port 8000'
    depends_on:
      - db_gateway
    environment:
      ML_DATABASE_URL: ${ML_DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      MODEL_PATH: ${MODEL_PATH}
      SHAP_ENABLED: ${SHAP_ENABLED}
