"""first

Revision ID: d10eac8566dd
Revises: 6429c0b8f538
Create Date: 2024-04-27 12:38:12.154184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd10eac8566dd'
down_revision: Union[str, None] = '6429c0b8f538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chambre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chambre_id'), 'chambre', ['id'], unique=False)
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('civilite', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('prenom', sa.String(), nullable=False),
    sa.Column('date_naissance', sa.DateTime(), nullable=False),
    sa.Column('admission', sa.DateTime(), nullable=False),
    sa.Column('sorti_le', sa.DateTime(), nullable=True),
    sa.Column('sortie_prevue_le', sa.DateTime(), nullable=True),
    sa.Column('chambre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chambre_id'], ['chambre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_id'), 'patient', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_id'), table_name='patient')
    op.drop_table('patient')
    op.drop_index(op.f('ix_chambre_id'), table_name='chambre')
    op.drop_table('chambre')
    # ### end Alembic commands ###
