services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  test:
    build:
      context: .
    depends_on:
      - redis
    command: pytest -s app/tests/

    develop:
      watch:
        - path: .
          action: rebuild
