"""correction relation circulaire chambre patient

Revision ID: 0b4d79482379
Revises: 0ab7c3a68d08
Create Date: 2025-01-18 21:31:25.083081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b4d79482379'
down_revision: Union[str, None] = '0ab7c3a68d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('patient_chambre_id_fkey', 'patient', type_='foreignkey')
    op.drop_column('patient', 'chambre_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('chambre_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('patient_chambre_id_fkey', 'patient', 'chambre', ['chambre_id'], ['id_chambre'], ondelete='CASCADE')
    # ### end Alembic commands ###
