"""empty message

Revision ID: 5dec7146f75d
Revises: ad15115ff09d
Create Date: 2026-04-01 04:51:12.456558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dec7146f75d'
down_revision: Union[str, None] = 'ad15115ff09d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_id_patient'), table_name='patient')
    op.drop_table('patient')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('id_patient', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_patient', name=op.f('patient_pkey'))
    )
    op.create_index(op.f('ix_patient_id_patient'), 'patient', ['id_patient'], unique=False)
    # ### end Alembic commands ###
