"""correction bug suppression table patient

Revision ID: 6fd74ad5f577
Revises: a9aa2d75382b
Create Date: 2026-04-01 11:51:41.491698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fd74ad5f577'
down_revision: Union[str, None] = 'a9aa2d75382b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_id_patient'), table_name='patient')
    op.drop_table('patient')
    op.add_column('reservation', sa.Column('ref', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('reservation_ref_patient_key'), 'reservation', type_='unique')
    op.drop_column('reservation', 'full_name')
    op.drop_column('reservation', 'ref_patient')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('ref_patient', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('reservation', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('reservation_ref_patient_key'), 'reservation', ['ref_patient'], postgresql_nulls_not_distinct=False)
    op.drop_column('reservation', 'ref')
    op.create_table('patient',
    sa.Column('id_patient', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ref_patient', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_patient', name=op.f('patient_pkey')),
    sa.UniqueConstraint('ref_patient', name=op.f('patient_ref_patient_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_patient_id_patient'), 'patient', ['id_patient'], unique=False)
    # ### end Alembic commands ###
