"""revamp de la db

Revision ID: 2578e5c69e4b
Revises: 001_initial
Create Date: 2026-03-19 00:28:28.207962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2578e5c69e4b'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_predictions_user_id'), table_name='validated_predictions')
    op.drop_index(op.f('idx_predictions_validation_date'), table_name='validated_predictions')
    op.drop_table('validated_predictions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validated_predictions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('predicted_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('validation_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('validated_predictions_pkey'))
    )
    op.create_index(op.f('idx_predictions_validation_date'), 'validated_predictions', ['validation_date'], unique=False)
    op.create_index(op.f('idx_predictions_user_id'), 'validated_predictions', ['user_id'], unique=False)
    # ### end Alembic commands ###
