"""ajout_ref_reservation_table_admission

Revision ID: 0217f398fc4e
Revises: 2ee258d5b264
Create Date: 2025-01-29 00:21:56.314859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0217f398fc4e'
down_revision: Union[str, None] = '2ee258d5b264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admission', sa.Column('ref_reservation', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admission', 'ref_reservation')
    # ### end Alembic commands ###
