"""empty message

Revision ID: 12425500cff3
Revises: d27c5619a407
Create Date: 2026-04-01 05:42:26.378796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12425500cff3'
down_revision: Union[str, None] = 'd27c5619a407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admission', 'nom_chambre')
    op.drop_column('admission', 'ref_chambre')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admission', sa.Column('ref_chambre', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('admission', sa.Column('nom_chambre', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
