"""email not unique

Revision ID: 1b6163bef3a0
Revises: 6c4528f4cdce
Create Date: 2024-12-02 09:40:02.986007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b6163bef3a0'
down_revision: Union[str, None] = '6c4528f4cdce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('patient_email_key', 'patient', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('patient_email_key', 'patient', ['email'])
    # ### end Alembic commands ###
