"""admissions_ajout_nom_chambre

Revision ID: 2ee258d5b264
Revises: 0088906d825f
Create Date: 2025-01-26 10:01:19.896106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ee258d5b264'
down_revision: Union[str, None] = '0088906d825f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admission', sa.Column('nom_chambre', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admission', 'nom_chambre')
    # ### end Alembic commands ###
