"""documents_type_document

Revision ID: 60fb0e1c57ac
Revises: d6a989ae5d3b
Create Date: 2024-11-08 12:51:58.551146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60fb0e1c57ac'
down_revision: Union[str, None] = 'd6a989ae5d3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('type_document', sa.Enum('ATTESTATION_CARTE_VITALE', 'AUTORISATION_DE_SOINS', 'AUTORISATION_DE_TRAITEMENT', 'AUTORISATION_DE_VISITE', 'AUTORISATION_DE_REMISE_A_NUIT', 'AUTORISATION_DE_DEPART', 'AUTORISATION_DE_DEBRANCHEMENT', 'AUTRE', name='documenttype'), nullable=False))
    op.alter_column('patient', 'civilite',
               existing_type=postgresql.ENUM('MONSIEUR', 'MADAME', 'AUTRE', 'ROBERTO', name='civilite'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient', 'civilite',
               existing_type=postgresql.ENUM('MONSIEUR', 'MADAME', 'AUTRE', 'ROBERTO', name='civilite'),
               nullable=True)
    op.drop_column('document', 'type_document')
    # ### end Alembic commands ###
