"""DocumentType Enum update

Revision ID: c389cf62ff0e
Revises: 60fb0e1c57ac
Create Date: 2024-11-08 15:24:22.623100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c389cf62ff0e'
down_revision: Union[str, None] = '60fb0e1c57ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
