"""preums

Revision ID: d6a989ae5d3b
Revises: 
Create Date: 2024-11-08 12:51:16.868751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6a989ae5d3b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_patient_nom'), 'patient', ['nom'], unique=False)
    op.create_index(op.f('ix_patient_prenom'), 'patient', ['prenom'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_prenom'), table_name='patient')
    op.drop_index(op.f('ix_patient_nom'), table_name='patient')
    # ### end Alembic commands ###
