"""ajout_nullable_to_ref_chambre_et_nom_chambre_table_admission

Revision ID: f24d36be25c2
Revises: 0217f398fc4e
Create Date: 2025-01-29 00:26:59.786932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f24d36be25c2'
down_revision: Union[str, None] = '0217f398fc4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admission', 'nom_chambre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admission', 'nom_chambre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
