networks:
  cmv:
    driver: bridge

volumes:
  db_patients:
    driver: local
  logs:
    driver: local

services:
  db_patients:
    image: postgres:17
    restart: always
    container_name: db_patients
    volumes:
      - db_patients:/var/lib/postgresql/data
    networks:
      - cmv
    ports:
      - "6002:5432"
    environment:
      POSTGRES_USER: ${DB_ADMIN_USERNAME}
      POSTGRES_PASSWORD: ${DB_ADMIN_PASSWORD}
      POSTGRES_DB: ${PATIENTS_POSTGRES_DB}

  api_patients:
    image: firizgoude/cmv_patients:latest
    pull_policy: always
    restart: always
    networks:
      - cmv
    volumes:
      - logs:/code/app/logs
    container_name: cmv_patients
    ports:
      - "8002:8000"
    command: >
      bash -c 'while !</dev/tcp/db_patients/5432; do sleep 1; done; uvicorn app.main:app --reload --host 0.0.0.0 --port 8000'
    depends_on:
      - db_patients
    environment:
      PATIENTS_DATABASE_URL: postgresql://${DB_CRUD_USERNAME}:${DB_CRUD_PASSWORD}@db_patients:5432/${PATIENTS_POSTGRES_DB}
      MIGRATION_DATABASE_URL: postgresql://${DB_ADMIN_USERNAME}:${DB_ADMIN_PASSWORD}@db_patients:5432/${PATIENTS_POSTGRES_DB}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
