volumes:
  pg-patients-dev:
    driver: local

# The containers that compose the project
services:
  db_patients:
    image: postgres:latest
    restart: always
    container_name: dev_pg-cmv_patients
    volumes:
      - pg-patients-dev:/var/lib/postgresql/data

    ports:
      - "6002:5432"
    environment:
      POSTGRES_USER: ${PATIENTS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PATIENTS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${PATIENTS_POSTGRES_DB}
