services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  test:
    build:
      context: .
    depends_on:
      - redis
    command: pytest -s app/tests/
    environment:
      - ENVIRONMENT=test
      - DATABASE_URL={TEST_DATABASE_URL}
    develop:
      watch:
        - path: .
          action: rebuild
