services:
  redis:
    image: valkey/valkey:latest
    ports:
      - "6379:6379"

  test:
    build:
      context: .
    depends_on:
      - redis
    command: pytest -s app/tests/
    environment:
      - ENVIRONMENT=test
      - DATABASE_URL={TEST_DATABASE_URL}
      - PATIENTS_SECRET_KEY="cle_tres_secrete cle_tres_secrete cle_tres_secrete cle_tres_secrete2"
      - CHAMBRES_SECRET_KEY="cle_tres_secrete cle_tres_secrete cle_tres_secrete cle_tres_secrete3"
      - ML_SECRET_KEY="cle_tres_secrete cle_tres_secrete cle_tres_secrete cle_tres_secrete4"

    develop:
      watch:
        - path: .
          action: rebuild
